<div id="slate_container"> 
	<div id="slate"> 
		<div id="slider">
			<a href="./"><img src="images/slate/slate6.jpg" alt="" title="#caption1" /></a>
			<a href="http://va.sdes.ucf.edu/"><img src="images/slate/slate1.jpg" alt="" title="#caption2" /></a>
			<a href="http://sarc.sdes.ucf.edu/"><img src="images/slate/slate2.jpg" alt="" title="#caption3" /></a>
			<a href="http://counseling.sdes.ucf.edu/"><img src="images/slate/slate3.jpg" alt="" title="#caption4" /></a>
			<a href="http://career.sdes.ucf.edu/"><img src="images/slate/slate4.jpg" alt="" title="#caption5" /></a>
			<a href="http://transfer.sdes.ucf.edu/"><img src="images/slate/slate5.jpg" alt="" title="#caption6" /></a>
			<a href="http://sds.sdes.ucf.edu/"><img src="images/slate/slate7.jpg" alt="" title="#caption7" /></a>
		</div>
	</div> 
</div>
    
<!-- SLATE-CAPTIONS -->	
<div class="nivo-html-caption" id="caption1">
	<div class="nivo-padding">
		<h2>Welcome to the Veteran Academic Resource Center</h2>
		<p>Here at the VARC, we are dedicated to accomodating your needs as a student veteran.</p>
	</div>
</div>

<div class="nivo-html-caption" id="caption2">
	<div class="nivo-padding">
		<h2>Veteran Services</h2>
		<p>To learn about your Veteran Educational Benefits, visit the Office of Veteran Services.</p>
	</div>
</div>

<div class="nivo-html-caption" id="caption3">
	<div class="nivo-padding">
		<h2>Student Academic Resource Center</h2>
		<p>To learn about services designed to help you achieve academic success, visit the Student Academic Resource Center.</p>
	</div>
</div>

<div class="nivo-html-caption" id="caption4">
	<div class="nivo-padding">
		<h2>Counseling Center</h2>
		<p>For a safe environment in which to address your personal concerns and how they affect
		you as a student, visit the Counseling Center.</p>
	</div>
</div>

<div class="nivo-html-caption" id="caption5">
	<div class="nivo-padding">
	<h2>Career Services</h2>
		<p>For help finding the right field of study, and to learn the practical application of your major, visit Career Services.</p>
	</div>
</div>

<div class="nivo-html-caption" id="caption6">
	<div class="nivo-padding">
		<h2>Transfer and Transition Services</h2>
		<p>For assistance in making a seamless transition to UCF, visit the Office of Transfer and Transition Services.</p>
	</div>
</div>

<div class="nivo-html-caption" id="caption7">
	<div class="nivo-padding">
		<h2>Student Disability Services</h2>
		<p>To learn about the various ways in which UCF can accomodate students with disabilities, visit Student Disability Services.</p>
	</div>
</div>
<!-- /SLATE-CAPTIONS -->