<div id="slate_container">
  <div id="slate">
    <div id="slider">
      <a href="./"><img src="images/billboard/06.jpg" alt="" title="#caption1" /></a>
      <img src="images/billboard/01.jpg" alt="" title="#caption2" />
      <img src="images/billboard/02.jpg" alt="" title="Sample title strapline." />
      <a href="http://caps.sdes.ucf.edu/"><img src="images/billboard/03.jpg" alt="" /></a>
      <a href="http://career.sdes.ucf.edu/"><img src="images/billboard/04.jpg" alt="" /></a>
      <img src="images/billboard/05.jpg" alt="" />
      <img src="images/billboard/07.jpg" alt="" />
    </div>
  </div>
</div>

<div class="nivo-html-caption" id="caption1">
  <div class="nivo-padding">
    <h2>Welcome to the Veteran Academic Resource Center</h2>
    <p>Here at the VARC, we are dedicated to accommodating your needs as a student veteran.</p>
  </div>
</div>

<div class="nivo-html-caption" id="caption2">
  <div class="nivo-padding">
    <h2>Veteran Services</h2>
    <p>To learn about your Veteran Educational Benefits, visit the Office of Veteran Services.</p>
  </div>
</div>